### ISSUE TITLE
Rework {{flp}} section

### ISSUE THREAD

**Issue by junyechen1996** [junyechen1996/draft-chen-cfrg-vdaf-pine#26]
should include the following checks:

- range check with lower bound `\beta_1`, upper bound `\beta_2`. See section 4.1 in paper.
- L2-norm check, which uses range check as-is, by plugging in the right `\beta_1` and `\beta_2`.
- wraparound check, which uses range check, and some other logic. See section 4.2 in paper.

**Comment by cjpatton** [comment]
Closing this issue because it's pretty stale.
